### ISSUE TITLE
Game seems to crash when right-clicking a filter pipe with an empty hand

### ISSUE THREAD

**Issue by SebastianDevus** [cakewhip/ezpas#32] opened 2021-12-18 04:13 UTC
[crash-2021-12-17_23.59.50-server.txt](https://github.com/cakewhip/ezpas/files/7738707/crash-2021-12-17_23.59.50-server.txt)

---- Minecraft Crash Report -------- Minecraft Crash Report ----// I let you down. Sorry :(
Time: 17/12/2021 23:59Description: Ticking block entity
java.lang.ClassCastException: class net.minecraft.class_2595 cannot be cast to class com.kqp.ezpas.block.entity.FilteredPipeBlockEntity (net.minecraft.class_2595 and com.kqp.ezpas.block.entity.FilteredPipeBlockEntity are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @39fcbef6) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:260) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:237) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:157) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.serverTick(PullerPipeBlockEntity.java:108) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.serverTick(PullerPipeBlockEntity.java:511) at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) at net.minecraft.class_1937.method_18471(class_1937.java:477) at net.minecraft.class_3218.method_18765(class_3218.java:365) at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) at net.minecraft.class_1132.method_3748(class_1132.java:99) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Server threadStacktrace: at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:260) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:237) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.calculateInsertionPoints(PullerPipeBlockEntity.java:157) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.serverTick(PullerPipeBlockEntity.java:108) at com.kqp.ezpas.block.entity.pullerpipe.PullerPipeBlockEntity.serverTick(PullerPipeBlockEntity.java:511) at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) at net.minecraft.class_1937.method_18471(class_1937.java:477) at net.minecraft.class_3218.method_18765(class_3218.java:365)
-- Block entity being ticked --Details: Name: ezpas:ender_puller_pipe // com.kqp.ezpas.block.entity.pullerpipe.EnderPullerPipeBlockEntity Block: Block{ezpas:ender_puller_pipe}[facing=up] Block location: World: (-57,-53,64), Section: (at 7,11,0 in -4,-4,4; chunk contains blocks -64,-64,64 to -49,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511) Block: Block{ezpas:ender_puller_pipe}[facing=up] Block location: World: (-57,-53,64), Section: (at 7,11,0 in -4,-4,4; chunk contains blocks -64,-64,64 to -49,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)Stacktrace: at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) at net.minecraft.class_1937.method_18471(class_1937.java:477) at net.minecraft.class_3218.method_18765(class_3218.java:365) at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) at net.minecraft.class_1132.method_3748(class_1132.java:99) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) at java.base/java.lang.Thread.run(Thread.java:833)
-- Affected level --Details: All players: 1 total; [class_3222['ThePainDoctor'/64, l='ServerLevel[Creative 1.18]', x=-54.18, y=-54.00, z=65.40]] Chunk stats: 3050 Level dimension: minecraft:overworld Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) Level time: 527831 game time, 279239 day time Level name: Creative 1.18 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false) Known server brands: fabric Level was modded: true Level storage version: 0x04ABD - AnvilStacktrace: at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) at net.minecraft.class_1132.method_3748(class_1132.java:99) at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) at java.base/java.lang.Thread.run(Thread.java:833)
-- System Details --Details: Minecraft Version: 1.18.1 Minecraft Version ID: 1.18.1 Operating System: Windows 10 (amd64) version 10.0 Java Version: 17.0.1, Microsoft Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft Memory: 976884752 bytes (931 MiB) / 1979711488 bytes (1888 MiB) up to 1979711488 bytes (1888 MiB) CPUs: 4 Processor Vendor: GenuineIntel Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz Identifier: Intel64 Family 6 Model 126 Stepping 5 Microarchitecture: Ice Lake (Client) Frequency (GHz): 1,19 Number of physical packages: 1 Number of physical CPUs: 2 Number of logical CPUs: 4 Graphics card #0 name: Intel(R) UHD Graphics Graphics card #0 vendor: Intel Corporation (0x8086) Graphics card #0 VRAM (MB): 1024,00 Graphics card #0 deviceId: 0x8a56 Graphics card #0 versionInfo: DriverVersion=27.20.100.8729 Memory slot #0 capacity (MB): 4096,00 Memory slot #0 clockSpeed (GHz): 2,67 Memory slot #0 type: DDR4 Virtual memory max (MB): 8657,95 Virtual memory used (MB): 7043,02 Swap memory total (MB): 4766,71 Swap memory used (MB): 1141,61 JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx1862M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M Fabric Mods:  addola: Addola 0.0.3-1.18 advancednetherite: Advanced Netherite 1.2.0-1.18 advancements-enlarger: Advancements Enlarger 0.2.4 allarrowsinfinityfix: All Arrows Infinity Fix 1.0.0 amecsapi: Amecs API 1.3.2+mc1.18-pre1 anvilrestoration-fabric: Anvil Restoration (Fabric) 1.1 apoli: Apoli 2.2.0 appleskin: AppleSkin mc1.18-2.2.0 architectury: Architectury 3.2.47 auto-crouch: Auto Crouch 2.0.0 backslot: BackSlot 1.2.3 balm-fabric: Balm 2.3.0+0 beaconoverhaul: Beacon Overhaul 1.5.0+1.18 beehivetooltips: Beehive Tooltips 1.4.1 betterbeaconplacement-fabric: Better Beacon Placement (Fabric) 1.4 betterbeds: Better Beds 1.2.0 betterconduitplacement-fabric: Better Conduit Placement (Fabric) 1.3 betterfpsdist: Better FPS distance Mod 1.18-1.3 betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.5 blue_endless_jankson: jankson 1.2.1 boatcontainer: BoatContainer 1.0.4 brokennametags: Broken Name Tags 1.0.2 calio: Calio 1.4.2 cardinal-components-base: Cardinal Components API (base) 4.0.0 cardinal-components-entity: Cardinal Components API (entities) 4.0.0 clearview: Lava Clear View 3.0.0 cloth-basic-math: cloth-basic-math 0.6.0 cloth-config: Cloth Config v6 6.0.45 clumps: Clumps 8.0.1 collective-fabric: Collective (Fabric) 3.14 com_electronwill_night-config_core: core 3.6.5 com_electronwill_night-config_toml: toml 3.6.5 com_eliotlash_mclib_mclib: mclib 18 com_eliotlash_molang_molang: molang 18 com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT comforts: Comforts 1.0.0-1.18 complete_bone_meal: Complete Bone Meal 1.3.0 compressed: Compressed 1.4.1 continuity: Continuity 1.0.3+1.18 cosmetic-armor: Cosmetic Armor 1.2.0 cpas: cpas 3.0.0 cpas-api: cpas-api 3.0.0 cpas-runtime: cpas-runtime 3.0.0 cpas-trinkets: cpas-trinkets 3.0.0 crimsonscrate: Crimsons Crate 1.18.1-Fabric-v1.0.0 crookedcrooks: Crooked Crooks 2.0.1+1.18.1 crowdin-translate: CrowdinTranslate 1.4+1.18 cryingportals-fabric: Crying Portals (Fabric) 1.0 cullleaves: Cull Leaves 2.3.2 customfence_fabric: Customfence 1-18-1 customizableelytra: Customizable Elytra 1.5.3-1.18 customportalapi: Custom Portal Api 0.0.1-beta47-1.18 cyclepaintings-fabric: Cycle Paintings (Fabric) 2.1 dmn_cha: Craftable Horse Armor 1.0.0 doubledoors-fabric: Double Doors (Fabric) 3.1 easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4 easyelytratakeoff-fabric: Easy Elytra Takeoff (Fabric) 2.2 easymagic: Easy Magic 3.0.0 enchantinginfuser: Enchanting Infuser 3.0.2 enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18 entityculling: EntityCulling-Fabric 1.3.3 exaltation: Exaltation 0.1.10 experiencebottler: Experience Bottler 1.18.1+build.1 ezpas: Ezpas 2.0.0 fabric: Fabric API 0.44.0+1.18 fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8 fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8 fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8 fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8 fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8 fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8 fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8 fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8 fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8 fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8 fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8 fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8 fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8 fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8 fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8 fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8 fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8 fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8 fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8 fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8 fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8 fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8 fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8 fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8 fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8 fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8 fabricloader: Fabric Loader 0.12.12 ferritecore: FerriteCore 4.0.0 fertilization: Fertilization 7.0.0 fiber: fiber 0.23.0-2 fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6 flight_rings: Flight Rings 1.6.1 forgeconfigapiport: Forge Config API Port 3.0.1 gbfabrictools: GBfabrictools 1.3.4+1.18 geckolib3: Geckolib 3.0.23 ghastly_wail: Ghastly Wail 1.0.5+MC1.18-1.18.1 goldenberries: Golden Berries 1.2.1+1.18.1 grassseeds-fabric: Grass Seeds (Fabric) 1.6 grid: Grid 1.18-fabric0.43.1-1.6.6 grindenchantments: Grind Enchantments 1.5.0+1.18 held-item-info: Held Item Info 1.2.0 hidearmor: Hide Armor 2.5 homing_ender_eye: Example Mod 1.0.0 horizontalpanes: Horizontal Panes 1.1.6 infinitetrading-fabric: Infinite Trading (Fabric) 2.1 jankson: Jankson 4.0.0+j1.2.0 java: OpenJDK 64-Bit Server VM 17 kelpfertilizer-fabric: Kelp Fertilizer (Fabric) 1.8 krypton: Krypton 0.1.6 lambdynlights: LambDynamicLights 2.1.0+1.17 lenientstacksize: Lenient Stack Size 1.3.0 libcd: LibCapableData 3.0.3+1.16.3 libgui: LibGui 5.1.0+1.18 libninepatch: LibNinePatch 1.1.0 litematica: Litematica 0.0.0-dev.20211203.013300 logical_zoom: Logical Zoom 0.0.13 magic_mirror: Magic Mirror 1.3.3b malilib: MaLiLib 0.10.0-dev.26 mcdict: MCDict 2.1.0+1.17.1 midnightlib: MidnightLib 0.2.9 minecraft: Minecraft 1.18.1 mining_dims: Mining Dimensions 1.2.36 mob_catcher: Mob Catcher 1.1.19 moborigins: Mob Origins 1.8.0 modmenu: Mod Menu 3.0.0 naturescompass: Nature's Compass 1.18.1-2.0.2-fabric offlineskins: OfflineSkins 1.18.1-v1-fabric omega-config: OmegaConfig 1.0.8 onastick: On A Stick 1.0.0 org_aperlambda_lambdajcommon: lambdajcommon 1.8.1 org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0 org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0 org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0 org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0 org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2 org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1 org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1 org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1 org_joml_joml: joml 1.10.2 org_reflections_reflections: reflections 0.10.2 origins: Origins 1.3.0 oxidized: Oxidized 1.5.0 pandamc_concreteplus: Concrete Plus 1.9.1 paperbooks-fabric: Paper Books (Fabric) 1.4 pettable: Pettable 1.2.1 pickupnotifier: Pick Up Notifier 3.0.0 pigemb: Piglin Emblem fabric-1.18.1-1.0 playerabilitylib: Pal 1.3.0 pride: Pride Lib 1.1.0+1.17 puzzleslib: Puzzles Lib 3.0.2 randombonemealflowers-fabric: Random Bone Meal Flowers (Fabric) 1.7 reach-entity-attributes: Reach Entity Attributes 2.1.1 recast-fabric: Recast (Fabric) 1.5 reeses-sodium-options: Reese's Sodium Options 1.2.3 replantingcrops-fabric: Replanting Crops (Fabric) 2.5 respawnablepets: Respawnable Pets 1.18-1 roughlyenoughitems: Roughly Enough Items 7.0.346 scaffoldingdropsnearby-fabric: Scaffolding Drops Nearby (Fabric) 1.5 simple_backpack: SimpleBackpack 1.2.25 skylorlib: SkyLib 1.0.6 slotlink: slotlink 4.0.1 smoothswapping: Smooth Swapping 0.4.3 sodium: Sodium 0.4.0-alpha5+build.9 sodium-extra: Sodium Extra 0.3.7 spawnermod: Enhanced Mob Spawners 1.1.2 spruceui: SpruceUI 3.3.0+1.17 staffofbuilding: Staff of Building 1.4.0-1.18.1 sturdygold: Sturdy Gold 0.3.0 sulfurpotassiummod: Sulfur & Potassium 1.1.1 superflatworldnoslimes-fabric: Superflat World No Slimes (Fabric) 1.5 teenycoal: Teeny Coal 1.0.3-1.16.x-1.17.x-1.18.x tntbreaksbedrock-fabric: TNT Breaks Bedrock (Fabric) 1.8 tokenablefurnaces: Tokenable Furnaces 1.1.5 totemplus: Totem Plus 1.2-1.18.1 tradingpost: Trading Post 3.0.0 trapexpansion: Trap Expansion 1.3.3 trinketofundying: Trinket of Undying 2.0.1-1.18 trinkets: Trinkets 3.1.0 umollu_ash: ASH - Another Simple HUD 1.1.16 viewbobbingmod: No Screen Bobbing 1.3 villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8 visualworkbench: Visual Workbench 3.0.0 waystones: Waystones 2.3.4 wthit: wthit 4.3.1 xaerominimap: Xaero's Minimap 21.22.3.1 zihlaunchpads: ZIHLaunchpads 1.2.0 Server Running: true Player Count: 1 / 8; [class_3222['ThePainDoctor'/64, l='ServerLevel[Creative 1.18]', x=-54.18, y=-54.00, z=65.40]] Data Packs: vanilla, Fabric Mods, file/VanillaTweaks_c663636.zip, file/anti ghast grief v1.1.2.zip, file/armor statues v2.8.3.zip, file/cauldron concrete v2.0.5.zip, file/double shulker shells v1.3.2.zip, file/fast leaf decay v2.0.5.zip, file/more mob heads v2.9.3.zip, file/redstone rotation wrench v1.1.3.zip, file/silence mobs v1.1.2.zip, file/terracotta rotation wrench v1.1.3.zip, file/unlock all recipes v2.0.3.zip Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by kavinphan** [comment] 2021-12-28 17:16
Duplicate of #31

**Closed as completed** 2021-12-28 17:18 UTC
