### ISSUE TITLE
Pipes don't respect Storage Cabinet's filtering

### ISSUE THREAD

**Issue by ghost** [cakewhip/ezpas#1] opened 2020-08-01 16:57 UTC
I'm not sure this is the right place to report it, or if it should be reported with Storage Cabinets (https://www.curseforge.com/minecraft/mc-mods/storage-cabinet).

![image](https://user-images.githubusercontent.com/918422/89106230-61a1de80-d428-11ea-816c-648fefb3d9d9.png)
This situation should be impossible.  Storage Cabinets would only allow items of the same type to be inserted into the same cabinet.  Trying to put these items in the same cabinet manually does not work.

Setup:
![image](https://user-images.githubusercontent.com/918422/89106267-c4937580-d428-11ea-9b69-0cfb9559406e.png)
The Storage Unit with wool isn't needed for this test.  The Storage Cabinet is locked, but pipes are able to insert unmatching items when they're unlocked as well.

**Comment by cakewhip** [comment] 2020-08-01 19:41
This is most likely a problem with EZPaS. I'm exploring a potential solution right now, thanks for the report. EDIT: fix worked, uploading to CurseForge now.

**Comment by ghost** [comment] 2020-08-01 20:18
Thank you !

**Comment by ghost** [comment] 2020-08-01 21:27
I might be doing something wrong, but it doesn't seem fixed for me:
![image](https://user-images.githubusercontent.com/918422/89110779-67121f80-d44e-11ea-807f-6f4915c935ca.png)

![image](https://user-images.githubusercontent.com/918422/89110785-742f0e80-d44e-11ea-96ca-4edae9f8e820.png)

I updated to ezpas-mc1.16.1-v1.0.4.jar and fabric-api-0.16.2+build.385-1.16.1.jar.

**Comment by cakewhip** [comment] 2020-08-01 21:53
I'm having trouble recreating this. Can you record all of the steps you took, such as what order you placed the blocks, put items in what block, etc.

![image](https://user-images.githubusercontent.com/25063862/89111091-24d5e780-d428-11ea-905e-59e61543bfd2.png)
![image](https://user-images.githubusercontent.com/25063862/89111092-27384180-d428-11ea-95dc-fdba5f88b82b.png)
![image](https://user-images.githubusercontent.com/25063862/89111093-29020500-d428-11ea-8e68-ec8e5a845277.png)

**Comment by ghost** [comment] 2020-08-01 22:25
Empty canvas: 
![image](https://user-images.githubusercontent.com/918422/89111313-9deb3400-d454-11ea-8907-d31177f49fa6.png)

I place an empty chest and empty cabinet
![image](https://user-images.githubusercontent.com/918422/89111322-b6f3e500-d454-11ea-9b20-c4cf23069019.png)

I put wool in the cabinet.
![image](https://user-images.githubusercontent.com/918422/89111328-c8d58800-d454-11ea-9ed3-42a1bbad57c5.png)

Then lock the cabinet (optional) by shift+right clicking the cabinet with the key
![image](https://user-images.githubusercontent.com/918422/89111334-e9054700-d454-11ea-9999-c9ff395bfe07.png)

I take out the wool, and put a puller pipe behind the chest, by shift+left clicking
![image](https://user-images.githubusercontent.com/918422/89111351-194ce580-d455-11ea-8857-49d178045233.png)

I connect the pipes between the puller and the cabinet, starting at the puller.
![image](https://user-images.githubusercontent.com/918422/89111362-3386c380-d455-11ea-98e9-e8e7a4ee495f.png)

I put wool and a random item in the chest
![image](https://user-images.githubusercontent.com/918422/89111374-5a44fa00-d455-11ea-85d4-5cf113d92067.png)

Everything gets transferred to the cabinet
![image](https://user-images.githubusercontent.com/918422/89111384-6a5cd980-d455-11ea-83fe-da3639a9996f.png)
![image](https://user-images.githubusercontent.com/918422/89111390-75176e80-d455-11ea-8a14-09600db5f0ae.png)


After this I've tried:
- removing the puller and replacing it with a normal click instead of shift click - same result
- doing this same procedure at a y > 1 (67) - same result
- reversing the order I put down the pipes - same result
- not locking the cabinet - same result

I did doublecheck I have ezpas-mc1.16.1-v1.0.4.jar on both client and server.  I'm attaching the logs here so you are convinced too.  I mean, at this point I'd seriously consider pebkac myself.
server: https://pastebin.com/9DQXRbBD
client: https://pastebin.com/npC4k1cR

**Comment by cakewhip** [comment] 2020-08-01 22:55
Thank you for all the details, but I am still unable to reproduce it in my environment. Could you load this [debug version](https://drive.google.com/file/d/1h3TxHO6s3elMAJLqxbZjKamPQi5ssyrm/view?usp=sharing) of EZPaS and send me the logs? You might have to pulse the puller block with redstone so it doesn't spam the log file.

**Comment by cakewhip** [comment] 2020-08-01 23:01
If you can, add me on Discord (KQP#1132) for faster comms.

**Comment by cakewhip** [comment] 2020-08-02 00:02
Closing as the issue is resolved on EZPaS's side.

**Closed as completed by cakewhip** 2020-08-02 00:02 UTC
